/*

 Modernizr 2.0.6 (Custom Build) | MIT & BSD
 Contains: fontface | backgroundsize | borderimage | borderradius | boxshadow | flexbox | hsla | multiplebgs | opacity | rgba | textshadow | cssanimations | csscolumns | generatedcontent | cssgradients | cssreflections | csstransforms | csstransforms3d | csstransitions | postmessage | touch | iepp | cssclasses | teststyles | testprop | testallprops | prefixes | domprefixes | load
*/
window.Modernizr=function(C,m,K){function y(b,e){var h=b.charAt(0).toUpperCase()+b.substr(1);b=(b+" "+O.join(h+" ")+h).split(" ");return w(b,e)}function w(b,e){for(var h in b)if(t[b[h]]!==K)return e=="pfx"?b[h]:true;return false}function P(b,e){return!!~(""+b).indexOf(e)}function R(b,e){return typeof b===e}function S(b,e){return G(v.join(b+";")+(e||""))}function G(b){t.cssText=b}var q={},D=m.documentElement;m.head||m.getElementsByTagName("head");var f=m.createElement("modernizr"),t=f.style,v=" -webkit- -moz- -o- -ms- -khtml- ".split(" "),
O="Webkit Moz O ms Khtml".split(" ");f={};var B=[],L=function(b,e,h,g){var s,i=m.createElement("div");if(parseInt(h,10))for(;h--;){s=m.createElement("div");s.id=g?g[h]:"modernizr"+(h+1);i.appendChild(s)}h=["&shy;<style>",b,"</style>"].join("");i.id="modernizr";i.innerHTML+=h;D.appendChild(i);b=e(i,b);i.parentNode.removeChild(i);return!!b},H,M={}.hasOwnProperty,N;!R(M,K)&&!R(M.call,K)?(N=function(b,e){return M.call(b,e)}):(N=function(b,e){return e in b&&R(b.constructor.prototype[e],K)});(function(b,
e){b=b.join("");var h=e.length;L(b,function(g,s){var i=m.styleSheets[m.styleSheets.length-1];i=i.cssRules&&i.cssRules[0]?i.cssRules[0].cssText:i.cssText||"";g=g.childNodes;for(var r={};h--;)r[g[h].id]=g[h];q.touch="ontouchstart"in C||r.touch.offsetTop===9;q.csstransforms3d=r.csstransforms3d.offsetLeft===9;q.generatedcontent=r.generatedcontent.offsetHeight>=1;q.fontface=/src/i.test(i)&&i.indexOf(s.split(" ")[0])===0},h,e)})(['@font-face {font-family:"font";src:url("https://")}',["@media (",v.join("touch-enabled),("),
"modernizr){#touch{top:9px;position:absolute}}"].join(""),["@media (",v.join("transform-3d),("),"modernizr){#csstransforms3d{left:9px;position:absolute}}"].join(""),'#generatedcontent:after{content:":)";visibility:hidden}'],["fontface","touch","csstransforms3d","generatedcontent"]);f.flexbox=function(){function b(i,r,E,F){i.style.cssText=v.join(r+":"+E+";")+(F||"")}function e(i,r,E,F){r+=":";i.style.cssText=(r+v.join(E+";"+r)).slice(0,-r.length)+(F||"")}var h=m.createElement("div"),g=m.createElement("div");
e(h,"display","box","width:42px;padding:0;");b(g,"box-flex","1","width:10px;");h.appendChild(g);D.appendChild(h);var s=g.offsetWidth===42;h.removeChild(g);D.removeChild(h);return s};f.touch=function(){return q.touch};f.postmessage=function(){return!!C.postMessage};f.rgba=function(){G("background-color:rgba(150,255,150,.5)");return P(t.backgroundColor,"rgba")};f.hsla=function(){G("background-color:hsla(120,40%,100%,.5)");return P(t.backgroundColor,"rgba")||P(t.backgroundColor,"hsla")};f.multiplebgs=
function(){G("background:url(https://),url(https://),red url(https://)");return/(url\s*\(.*?){3}/.test(t.background)};f.backgroundsize=function(){return y("backgroundSize")};f.borderimage=function(){return y("borderImage")};f.borderradius=function(){return y("borderRadius")};f.boxshadow=function(){return y("boxShadow")};f.textshadow=function(){return m.createElement("div").style.textShadow===""};f.opacity=function(){S("opacity:.55");return/^0.55$/.test(t.opacity)};f.cssanimations=function(){return y("animationName")};
f.csscolumns=function(){return y("columnCount")};f.cssgradients=function(){G(("background-image:"+v.join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+v.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17));return P(t.backgroundImage,"gradient")};f.cssreflections=function(){return y("boxReflect")};f.csstransforms=function(){return!!w(["transformProperty","WebkitTransform","MozTransform","OTransform","msTransform"])};f.csstransforms3d=function(){var b=
!!w(["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"]);b&&"webkitPerspective"in D.style&&(b=q.csstransforms3d);return b};f.csstransitions=function(){return y("transitionProperty")};f.fontface=function(){return q.fontface};f.generatedcontent=function(){return q.generatedcontent};for(var T in f)N(f,T)&&(H=T.toLowerCase(),q[H]=f[T](),B.push((q[H]?"":"no-")+H));G("");f=null;C.attachEvent&&function(){var b=m.createElement("div");b.innerHTML="<elem></elem>";return b.childNodes.length!==
1}()&&function(b,e){function h(n){for(var o=-1;++o<r;)n.createElement(i[o])}b.iepp=b.iepp||{};var g=b.iepp,s=g.html5elements||"abbr|article|aside|audio|canvas|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",i=s.split("|"),r=i.length,E=new RegExp("(^|\\s)("+s+")","gi"),F=new RegExp("<(/*)("+s+")","gi"),U=/^\s*[\{\}]\s*$/,V=new RegExp("(^|[^\\n]*?\\s)("+s+")([^\\n]*)({[\\n\\w\\W]*?})","gi"),z=e.createDocumentFragment(),a=e.documentElement;
s=a.firstChild;var d=e.createElement("body"),j=e.createElement("style"),A=/print|all/,u;g.getCSS=function(n,o){if(n+""===K)return"";for(var c=-1,k=n.length,l,x=[];++c<k;){l=n[c];if(!l.disabled){o=l.media||o;A.test(o)&&x.push(g.getCSS(l.imports,o),l.cssText);o="all"}}return x.join("")};g.parseCSS=function(n){for(var o=[],c;(c=V.exec(n))!=null;)o.push(((U.exec(c[1])?"\n":c[1])+c[2]+c[3]).replace(E,"$1.iepp_$2")+c[4]);return o.join("\n")};g.writeHTML=function(){var n=-1;for(u=u||e.body;++n<r;)for(var o=
e.getElementsByTagName(i[n]),c=o.length,k=-1;++k<c;)o[k].className.indexOf("iepp_")<0&&(o[k].className+=" iepp_"+i[n]);z.appendChild(u);a.appendChild(d);d.className=u.className;d.id=u.id;d.innerHTML=u.innerHTML.replace(F,"<$1font")};g._beforePrint=function(){j.styleSheet.cssText=g.parseCSS(g.getCSS(e.styleSheets,"all"));g.writeHTML()};g.restoreHTML=function(){d.innerHTML="";a.removeChild(d);a.appendChild(u)};g._afterPrint=function(){g.restoreHTML();j.styleSheet.cssText=""};h(e);h(z);g.disablePP||
(s.insertBefore(j,s.firstChild),j.media="print",j.className="iepp-printshim",b.attachEvent("onbeforeprint",g._beforePrint),b.attachEvent("onafterprint",g._afterPrint))}(C,m);q._version="2.0.6";q._prefixes=v;q._domPrefixes=O;q.testProp=function(b){return w([b])};q.testAllProps=y;q.testStyles=L;D.className=D.className.replace(/\bno-js\b/,"")+(" js "+B.join(" "));return q}(this,this.document);
(function(C,m,K){function y(a){return!a||a=="loaded"||a=="complete"}function w(){for(var a=1,d=-1;B.length-++d;)if(B[d].s&&!(a=B[d].r))break;a&&S()}function P(a){var d=m.createElement("script"),j;d.src=a.s;d.onreadystatechange=d.onload=function(){!j&&y(d.readyState)&&(j=1,w(),d.onload=d.onreadystatechange=null)};t(function(){j||(j=1,w())},z.errorTimeout);a.e?d.onload():v.parentNode.insertBefore(d,v)}function R(a){var d=m.createElement("link"),j;d.href=a.s;d.rel="stylesheet";d.type="text/css";if(!a.e&&
(b||H)){var A=function(u){t(function(){if(!j)try{u.sheet.cssRules.length?(j=1,w()):A(u)}catch(n){n.code==1E3||n.message=="security"||n.message=="denied"?(j=1,t(function(){w()},0)):A(u)}},0)};A(d)}else{d.onload=function(){j||(j=1,t(function(){w()},0))};a.e&&d.onload()}t(function(){j||(j=1,w())},z.errorTimeout);!a.e&&v.parentNode.insertBefore(d,v)}function S(){var a=B.shift();L=1;a?a.t?t(function(){a.t=="c"?R(a):P(a)},0):(a(),w()):(L=0)}function G(a,d,j,A,u,n){function o(){!k&&y(c.readyState)&&(l.r=
k=1,!L&&w(),c.onload=c.onreadystatechange=null,t(function(){N.removeChild(c)},0))}var c=m.createElement(a),k=0,l={t:j,s:d,e:n};c.src=c.data=d;!M&&(c.style.display="none");c.width=c.height="0";a!="object"&&(c.type=j);c.onload=c.onreadystatechange=o;a=="img"?(c.onerror=o):a=="script"&&(c.onerror=function(){l.e=l.r=1;S()});B.splice(A,0,l);N.insertBefore(c,M?null:v);t(function(){k||(N.removeChild(c),l.r=l.e=k=1,w())},z.errorTimeout)}function q(a,d,j){var A=d=="c"?g:h;L=0;d=d||"j";r(a)?G(A,a,d,this.i++,
f,j):(B.splice(this.i++,0,a),B.length==1&&S());return this}function D(){var a=z;a.loader={load:q,i:0};return a}var f=m.documentElement,t=C.setTimeout,v=m.getElementsByTagName("script")[0],O={}.toString,B=[],L=0,H="MozAppearance"in f.style,M=H&&!!m.createRange().compareNode,N=M?f:v.parentNode,T=C.opera&&O.call(C.opera)=="[object Opera]",b="webkitAppearance"in f.style,e=b&&"async"in m.createElement("script"),h=H?"object":T||e?"img":"script",g=b?"img":h,s=Array.isArray||function(a){return O.call(a)==
"[object Array]"},i=function(a){return Object(a)===a},r=function(a){return typeof a=="string"},E=function(a){return O.call(a)=="[object Function]"},F=[],U={},V,z;z=function(a){function d(c){c=c.split("!");var k=F.length,l=c.pop(),x=c.length;l={url:l,origUrl:l,prefixes:c};var I,p;for(p=0;p<x;p++)(I=U[c[p]])&&(l=I(l));for(p=0;p<k;p++)l=F[p](l);return l}function j(c,k,l,x,I){var p=d(c),J=p.autoCallback;if(!p.bypass){k&&(k=E(k)?k:k[c]||k[x]||k[c.split("/").pop().split("?")[0]]);if(p.instead)return p.instead(c,
k,l,x,I);l.load(p.url,p.forceCSS||!p.forceJS&&/css$/.test(p.url)?"c":K,p.noexec);(E(k)||E(J))&&l.load(function(){D();k&&k(p.origUrl,I,x);J&&J(p.origUrl,I,x)})}}function A(c,k){function l(Q){if(r(Q))j(Q,p,k,0,x);else if(i(Q))for(J in Q)Q.hasOwnProperty(J)&&j(Q[J],p,k,J,x)}var x=!!c.test,I=c.load||c.both,p=c.callback,J;l(x?c.yep:c.nope);l(I);c.complete&&k.load(c.complete)}var u,n,o=this.yepnope.loader;if(r(a))j(a,0,o,0);else if(s(a))for(u=0;u<a.length;u++){n=a[u];r(n)?j(n,0,o,0):s(n)?z(n):i(n)&&A(n,
o)}else i(a)&&A(a,o)};z.addPrefix=function(a,d){U[a]=d};z.addFilter=function(a){F.push(a)};z.errorTimeout=1E4;m.readyState==null&&m.addEventListener&&(m.readyState="loading",m.addEventListener("DOMContentLoaded",V=function(){m.removeEventListener("DOMContentLoaded",V,0);m.readyState="complete"},0));C.yepnope=D()})(this,this.document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};